In [1]:

# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [2]:

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM,Dense

In [3]:

# univariate data preparation
from numpy import array
 
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
n_features = 1
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [4]:

# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')


In [5]:

# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))


In [6]:
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction


In [12]:
import numpy as np
x_input = array([70, 80, 90])
x_input = x_input.reshape((1, n_steps, n_features)).astype(np.float32)


In [13]:
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[102.79045]]


In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import LSTM,Dense

In [17]:
import pandas as pd
df=pd.read_csv('iris.data')
X=df.drop('label',axis=1)
y=df['label']

KeyError: "['label'] not found in axis"

In [7]:
model = Sequential()
model.add(Dense(12, input_dim=2, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X, y, epochs=150, batch_size=10)

Train on 16 samples
Epoch 1/150
16/16 [==============================] - 1s 32ms/sample - loss: -2.1642 - accuracy: 0.5000
Epoch 2/150
16/16 [==============================] - 0s 431us/sample - loss: -2.3439 - accuracy: 0.5000
Epoch 3/150
16/16 [==============================] - 0s 310us/sample - loss: -2.5079 - accuracy: 0.5000
Epoch 4/150
16/16 [==============================] - 0s 398us/sample - loss: -2.7268 - accuracy: 0.5000
Epoch 5/150
16/16 [==============================] - 0s 371us/sample - loss: -2.9131 - accuracy: 0.5000
Epoch 6/150
16/16 [==============================] - 0s 436us/sample - loss: -3.0840 - accuracy: 0.5000
Epoch 7/150
16/16 [==============================] - 0s 401us/sample - loss: -3.2769 - accuracy: 0.5000
Epoch 8/150
16/16 [==============================] - 0s 436us/sample - loss: -3.4797 - accuracy: 0.5000
Epoch 9/150
16/16 [==============================] - 0s 377us/sample - loss: -3.6781 - accuracy: 0.5000
Epoch 10/150
16/16 [=========================

16/16 [==============================] - 0s 250us/sample - loss: -25.5008 - accuracy: 0.5000
Epoch 77/150
16/16 [==============================] - 0s 248us/sample - loss: -25.7131 - accuracy: 0.5000
Epoch 78/150
16/16 [==============================] - 0s 312us/sample - loss: -26.0406 - accuracy: 0.5000
Epoch 79/150
16/16 [==============================] - 0s 300us/sample - loss: -26.1127 - accuracy: 0.5000
Epoch 80/150
16/16 [==============================] - 0s 479us/sample - loss: -26.4064 - accuracy: 0.5000
Epoch 81/150
16/16 [==============================] - 0s 537us/sample - loss: -26.5317 - accuracy: 0.5000
Epoch 82/150
16/16 [==============================] - 0s 436us/sample - loss: -26.6591 - accuracy: 0.5000
Epoch 83/150
16/16 [==============================] - 0s 436us/sample - loss: -26.8284 - accuracy: 0.5000
Epoch 84/150
16/16 [==============================] - 0s 497us/sample - loss: -26.9325 - accuracy: 0.5000
Epoch 85/150
16/16 [==============================] - 0s 43

In [8]:
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

16/16 [==============================] - 0s 7ms/sample - loss: -29.7280 - accuracy: 0.5000
Accuracy: 50.00


In [16]:
model.add(Dense(12,input_dim=8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='softmax'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=150, batch_size=10)

Train on 16 samples
Epoch 1/150
16/16 [==============================] - 1s 82ms/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 2/150
16/16 [==============================] - 0s 625us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 3/150
16/16 [==============================] - 0s 646us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 4/150
16/16 [==============================] - 0s 563us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 5/150
16/16 [==============================] - 0s 623us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 6/150
16/16 [==============================] - 0s 562us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 7/150
16/16 [==============================] - 0s 563us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 8/150
16/16 [==============================] - 0s 564us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 9/150
16/16 [==============================] - 0s 559us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 10/150
16/16 [================

16/16 [==============================] - 0s 1ms/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 77/150
16/16 [==============================] - 0s 1ms/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 78/150
16/16 [==============================] - 0s 997us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 79/150
16/16 [==============================] - 0s 935us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 80/150
16/16 [==============================] - 0s 928us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 81/150
16/16 [==============================] - 0s 938us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 82/150
16/16 [==============================] - 0s 882us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 83/150
16/16 [==============================] - 0s 875us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 84/150
16/16 [==============================] - 0s 873us/sample - loss: -30.6665 - accuracy: 0.5000
Epoch 85/150
16/16 [==============================] - 0s 873us/

In [14]:
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

16/16 [==============================] - 0s 14ms/sample - loss: -30.6665 - accuracy: 0.5000
Accuracy: 50.00


In [28]:

import pandas
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier
#from tensorflow.keras.utils import np_utils
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import LabelEncoder
from sklearn.pipeline import Pipeline

In [29]:
dataframe = pandas.read_csv("iris.data", header=None)
dataset = dataframe.values
X = dataset[:,0:4].astype(float)
Y = dataset[:,4]

In [30]:
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [38]:
def baseline_model():
	# create model
    model = Sequential()
    model.add(Dense(8, input_dim=4, activation='relu'))
    model.add(Dense(12, activation='relu'))
    model.add(Dense(3, activation='softmax'))
	# Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [44]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(12, activation='relu'))
model.add(Dense(3, activation='softmax'))
	# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X,dummy_y)

Train on 150 samples
150/150 [==============================] - 1s 7ms/sample - loss: 2.4350 - accuracy: 0.3333


In [48]:
estimator = KerasClassifier(build_fn=baseline_model, epochs=200, batch_size=5, verbose=0)

In [49]:
kfold = KFold(n_splits=10, shuffle=True)

In [50]:
results = cross_val_score(estimator, X, dummy_y, cv=kfold)
print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

Baseline: 97.33% (4.42%)
